print:
	@echo "Hello"

audit:
	@echo "example00"
	@echo " "
	@go run . "example/example00.txt"
	@echo " "
	@echo "example01"
	@echo " "
	@go run . "example/example01.txt"
	@echo " "
	@echo "example02"
	@echo " "
	@go run . "example/example02.txt"
	@echo " "
	@echo "example03"
	@echo " "
	@go run . "example/example03.txt"
	@echo " "
	@echo "example04"
	@echo " "
	@go run . "example/example04.txt"
	@echo " "
	@echo "example05"
	@echo " "
	@go run . "example/example05.txt"
	@echo " "
	@echo "example06"
	@echo " "
	@go run . "example/example06.txt"
	@echo " "
	@echo "example07"
	@echo " "
	@go run . "example/example07.txt"
	